modLoader="javafml" 
loaderVersion="[40,)" 
license="GPL-3.0 License"
issueTrackerURL="https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.19.2/issues"
[[mods]] 
modId="matteroverdrive"
version="${file.jarVersion}" 
displayName="MatterOverdrive: Community Edition" 
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/matter-overdrive-community-edition" #optional
logoFile="mo_logo.png" 
credits="A mod that dwells within matter and energy."
authors="skip999, SeaRobber69, Sekwah41, Lanse505, NinjaOnion, AurilisDev, InfiniteBlock, VanMuur, Gandalf360one, Horizon Studio, Coded, Buuz135, Simeon Radivoev, Shadowfacts, Dev_Osmium"
description='''
Matter Overdrive is a Star Trek themed mod based around manipulating matter and energy.
'''
